services:
  quarkus-service:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://demo-db:5432/demo
      - QUARKUS_DATASOURCE_DB_KIND=postgresql
      - QUARKUS_DATASOURCE_USERNAME=postgres
      - QUARKUS_DATASOURCE_PASSWORD=root
    ports:
      - "8080:8080"  # the HTTP endpoint
      - "5005:5005"  # the Debugging endpoint
    depends_on: [demo-db]

  demo-db:
    image: "postgres:15-alpine"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=demo
    ports:
      - "5433:5432"
    restart: always
