version: "3.8"

services:
  quarkus-service:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://demo-db:5432/demo
    ports:
      - "8080:8080"  # the HTTP endpoint
    depends_on: [demo-db]

  demo-db:
    image: "postgres:10.5"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=demo
    ports:
      - "5433:5432"
